name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: test
      run: |
        sbt test

  BuildAndDeploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: LintAndTest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: assembly
      run: |
        sbt "clean; set (assembly / test) := {}; assembly"
    - name: deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/scala-2.13/bendingunit22-assembly-0.1.jar
        remote: /tmp/${{ github.sha }}.jar
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
    - name: update app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cp /tmp/${{ github.sha }}.jar ~/bender/app.jar
          sudo systemctl restart bender
    - name: inform command
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.INFORM_CHAT_ID }}
        token: ${{ secrets.TG_BOT_API_TOKEN }}
        message: |
          New release is deployed 🚀
          Commit SHA = ${{ github.sha }}
