name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  LintAndTest:
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-17.0.15_6_1.11.1_2.13.16
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
    - name: run tests
      run: sbt test

  BuildAndDeploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: LintAndTest
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-17.0.15_6_1.11.1_2.13.16
    steps:
    - name: checkout the code
      uses: actions/checkout@v3
    - name: Assembly
      run: sbt "clean; set (assembly / test) := {}; assembly"
    - name: Deploy
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: target/scala-2.13/bendingunit22-assembly-0.1.jar
        target: /tmp
        strip_components: 2
    - name: Update app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cp /tmp/bendingunit22-assembly-0.1.jar ~/bender/app.jar
          sudo systemctl restart bender
    - name: Inform command
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.INFORM_CHAT_ID }}
        token: ${{ secrets.TG_BOT_API_TOKEN }}
        message: |
          New release is deployed 🚀
          Commit SHA = ${{ github.sha }}
